# https://taskfile.dev

version: "3"

vars:
  WEBROOT: "./www"

tasks:
  book:
    dir: ./book
    cmds:
      - mdbook build

  clean:
    cmds:
      - rm -rf {{.WEBROOT}}

  pack:
    cmds:
      - wasm-pack build --target web
    generates:
      - pkg/**
      - target/**
    sources:
      - Cargo.toml
      - Cargo.lock
      - src/**

  default:
    deps: [clean, book]
    cmds:
      - yarn build
      - mkdir -p {{.WEBROOT}}/book
      - cp -R book/book/* {{.WEBROOT}}/book
